-- Generated by yahr-theme; do not edit.
return {
    accent_rose     = "rgb(f5e0dc)",
    accent_coral    = "rgb(f2cdcd)",
    accent_pink     = "rgb(f5c2e7)",
    accent_purple   = "rgb(cba6f7)",
    accent_red      = "rgb(f38ba8)",
    accent_maroon   = "rgb(eba0ac)",
    accent_orange   = "rgb(fab387)",
    accent_yellow   = "rgb(f9e2af)",
    accent_green    = "rgb(a6e3a1)",
    accent_teal     = "rgb(94e2d5)",
    accent_cyan     = "rgb(89dceb)",
    accent_sapphire = "rgb(74c7ec)",
    accent_blue     = "rgb(89b4fa)",
    accent_lavender = "rgb(b4befe)",

    fg_primary   = "rgb(cdd6f4)",
    fg_secondary = "rgb(bac2de)",
    fg_tertiary  = "rgb(a6adc8)",

    border_2 = "rgb(9399b2)",
    border_1 = "rgb(7f849c)",
    border_0 = "rgb(6c7086)",

    surface_2 = "rgb(585b70)",
    surface_1 = "rgb(45475a)",
    surface_0 = "rgb(313244)",

    bg_base   = "rgb(1e1e2e)",
    bg_mantle = "rgb(181825)",
    bg_crust  = "rgb(11111b)",

    glass_accent = "rgba(89b4fa59)",
}
