[General]
Background="login-background.png"
HeroBackground="login-background.png"
BackgroundBlur=0

ThemeColor="#6db3ce"
AccentColor="#a78cfa"
BgBase="#181625"
BgSurface="#2b2837"
FgPrimary="#cdcbe0"
FgSecondary="#aeafca"
FailColor="#eb746b"

WidgetOpacity=0.75

Font="Inter"
TitleFont="Inter ExtraBold"
FontSize=13
TitleFontSize=56

EnableAvatars=true
ShowHostname=false
ShowSessionButton=true
ShowPowerButtons=true

TimeFormat="h:mm AP"
DateFormat="ddd  MM/dd/yyyy"

TranslateLogin=
TranslateLoginFailed=
TranslateUsername=
TranslatePassword=
TranslateSession=
TranslateSuspend=
TranslateReboot=
TranslateShutdown=
