"""String templates rendered from a palette JSON object."""

from __future__ import annotations

from .colors import rgb_css, strip_hash


def _h(palette: dict, key: str) -> str:
    return strip_hash(palette[key])


def hypr_theme_lua(palette: dict) -> str:
    def rgb(key: str) -> str:
        return rgb_css(palette[key])

    blue = _h(palette, "accentBlue")
    return f'''-- Generated by yahr-theme; do not edit.
return {{
    accent_rose     = "{rgb("accentRose")}",
    accent_coral    = "{rgb("accentCoral")}",
    accent_pink     = "{rgb("accentPink")}",
    accent_purple   = "{rgb("accentPurple")}",
    accent_red      = "{rgb("accentRed")}",
    accent_maroon   = "{rgb("accentMaroon")}",
    accent_orange   = "{rgb("accentOrange")}",
    accent_yellow   = "{rgb("accentYellow")}",
    accent_green    = "{rgb("accentGreen")}",
    accent_teal     = "{rgb("accentTeal")}",
    accent_cyan     = "{rgb("accentCyan")}",
    accent_sapphire = "{rgb("accentSapphire")}",
    accent_blue     = "{rgb("accentBlue")}",
    accent_lavender = "{rgb("accentLavender")}",

    fg_primary   = "{rgb("fgPrimary")}",
    fg_secondary = "{rgb("fgSecondary")}",
    fg_tertiary  = "{rgb("fgTertiary")}",

    border_2 = "{rgb("border2")}",
    border_1 = "{rgb("border1")}",
    border_0 = "{rgb("border0")}",

    surface_2 = "{rgb("surface2")}",
    surface_1 = "{rgb("surface1")}",
    surface_0 = "{rgb("surface0")}",

    bg_base   = "{rgb("bgBase")}",
    bg_mantle = "{rgb("bgMantle")}",
    bg_crust  = "{rgb("bgCrust")}",

    glass_accent = "rgba({blue}59)",
}}
'''


def kitty_theme(palette: dict) -> str:
    fg = palette["fgPrimary"]
    bg = palette["bgBase"]
    acc = palette["accentBlue"]
    crust = palette["bgCrust"]
    red = palette["accentRed"]
    green = palette["accentGreen"]
    yellow = palette["accentYellow"]
    purple = palette["accentPurple"]
    cyan = palette["accentCyan"]
    return f'''# Generated by yahr-theme — {palette["name"]}
foreground {fg}
background {bg}
selection_foreground {bg}
selection_background {acc}
cursor {fg}
cursor_text_color {bg}

color0 {crust}
color8 {palette["surface1"]}

color1 {red}
color9 {red}

color2 {green}
color10 {green}

color3 {yellow}
color11 {yellow}

color4 {acc}
color12 {acc}

color5 {purple}
color13 {purple}

color6 {cyan}
color14 {cyan}

color7 {fg}
color15 {fg}
'''


def mako_config(palette: dict) -> str:
    bg = strip_hash(palette["bgBase"])
    fg = palette["fgPrimary"]
    acc = strip_hash(palette["accentBlue"])
    green = strip_hash(palette["accentGreen"])
    red = strip_hash(palette["accentRed"])
    return f'''# Generated by yahr-theme — {palette["name"]}
font=Maple Mono NF 13
markup=1
max-visible=5
sort=-time
layer=overlay
anchor=top-right
margin=8
padding=14
border-size=1
border-radius=16
background-color=#{bg}E8
text-color={fg}
border-color=#{acc}59
progress-color=over #{acc}59

default-timeout=10000
width=400
height=150
max-icon-size=48
group-by=app-name

[urgency=low]
border-color=#{green}59
default-timeout=5000

[urgency=normal]
border-color=#{acc}59
default-timeout=10000

[urgency=critical]
border-color=#{red}99
default-timeout=0

icons=1
icon-path=/usr/share/icons/Papirus-Dark
format=<b>%s</b>\\n%b
'''


def gtk_css(palette: dict) -> str:
    """GTK3/GTK4 overlay on top of adw-gtk3-dark."""
    return f'''/* Generated by yahr-theme — {palette["name"]} */
@define-color accent_color {palette["accentBlue"]};
@define-color accent_bg_color {palette["accentBlue"]};
@define-color accent_fg_color {palette["bgBase"]};
@define-color window_bg_color {palette["bgBase"]};
@define-color window_fg_color {palette["fgPrimary"]};
@define-color view_bg_color {palette["bgMantle"]};
@define-color view_fg_color {palette["fgPrimary"]};
@define-color headerbar_bg_color {palette["bgMantle"]};
@define-color headerbar_fg_color {palette["fgPrimary"]};
@define-color headerbar_backdrop_color {palette["bgCrust"]};
@define-color headerbar_border_color {palette["border0"]};
@define-color card_bg_color {palette["surface0"]};
@define-color card_fg_color {palette["fgPrimary"]};
@define-color popover_bg_color {palette["surface0"]};
@define-color popover_fg_color {palette["fgPrimary"]};
@define-color sidebar_bg_color {palette["bgMantle"]};
@define-color sidebar_fg_color {palette["fgPrimary"]};
@define-color sidebar_backdrop_color {palette["bgCrust"]};
@define-color destructive_bg_color {palette["accentRed"]};
@define-color destructive_fg_color {palette["bgBase"]};
@define-color success_bg_color {palette["accentGreen"]};
@define-color warning_bg_color {palette["accentYellow"]};
@define-color error_bg_color {palette["accentRed"]};
@define-color borders {palette["border0"]};

* {{
  color: {palette["fgPrimary"]};
}}

window, .background, .csd {{
  background-color: {palette["bgBase"]};
  color: {palette["fgPrimary"]};
}}

headerbar, .titlebar {{
  background-color: {palette["bgMantle"]};
  color: {palette["fgPrimary"]};
}}

.sidebar, placessidebar, treeview {{
  background-color: {palette["bgMantle"]};
}}

entry, .entry {{
  background-color: {palette["surface0"]};
  color: {palette["fgPrimary"]};
  border-color: {palette["border0"]};
}}

button {{
  background-image: none;
  background-color: {palette["surface1"]};
  color: {palette["fgPrimary"]};
}}

button:hover {{
  background-color: {palette["surface2"]};
}}

button.suggested-action, button.default {{
  background-color: {palette["accentBlue"]};
  color: {palette["bgBase"]};
}}

selection, *:selected {{
  background-color: {palette["accentBlue"]};
  color: {palette["bgBase"]};
}}
'''


def gtk_settings_ini() -> str:
    return """[Settings]
gtk-theme-name=adw-gtk3-dark
gtk-icon-theme-name=Papirus-Dark
gtk-font-name=Inter 11
gtk-cursor-theme-name=Adwaita
gtk-cursor-theme-size=24
gtk-application-prefer-dark-theme=1
"""


def hyprlock_conf(palette: dict) -> str:
    bg = strip_hash(palette["bgBase"])
    acc = strip_hash(palette["accentBlue"])
    green = strip_hash(palette["accentGreen"])
    red = strip_hash(palette["accentRed"])
    fg = strip_hash(palette["fgPrimary"])
    fg2 = strip_hash(palette["fgSecondary"])
    fg3 = strip_hash(palette["fgTertiary"])
    return f'''# Generated by yahr-theme — {palette["name"]}
$font = Maple Mono NF

general {{
    hide_cursor = false
}}

animations {{
    enabled = true
    bezier = easeInOut, 0.42, 0, 0.58, 1
    animation = fadeIn, 1, 4, easeInOut
    animation = fadeOut, 1, 4, easeInOut
    animation = inputFieldDots, 1, 2, easeInOut
}}

background {{
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
}}

input-field {{
    monitor =
    size = 350, 50
    outline_thickness = 2
    inner_color = rgba({bg}E6)
    outer_color = rgba({acc}FF)
    check_color = rgba({green}FF)
    fail_color = rgba({red}FF)
    font_color = rgba({fg}FF)
    fade_on_empty = false
    rounding = 12
    font_family = $font
    placeholder_text = Enter Password...
    fail_text = <span foreground="#{red}"><b>$FAIL ($ATTEMPTS)</b></span>
    dots_spacing = 0.3
    dots_center = true
    position = 0, -100
    halign = center
    valign = center
}}

label {{
    monitor =
    text = cmd[update:1000] date +"%I:%M %p"
    color = rgba({fg}FF)
    font_size = 120
    font_family = $font
    position = 0, 250
    halign = center
    valign = center
}}

label {{
    monitor =
    text = cmd[update:60000] date +"%m/%d/%Y"
    color = rgba({fg2}E6)
    font_size = 28
    font_family = $font
    position = 0, 120
    halign = center
    valign = center
}}

label {{
    monitor =
    text = $USER
    color = rgba({fg3}CC)
    font_size = 18
    font_family = $font
    position = 0, -200
    halign = center
    valign = center
}}
'''


def qt6ct_colors(palette: dict) -> str:
    def argb(key: str) -> str:
        return "#ff" + strip_hash(palette[key])

    fg = argb("fgPrimary")
    bg = argb("bgBase")
    acc = argb("accentBlue")
    surface = argb("surface0")
    mantle = argb("bgMantle")
    disabled = argb("fgTertiary")
    return f"""[ColorScheme]
active_colors={fg}, {bg}, {fg}, {fg}, {disabled}, {fg}, {fg}, {fg}, {fg}, {bg}, {bg}, {mantle}, {surface}, {fg}, {acc}, {acc}, {mantle}, {fg}, {surface}, {fg}, {acc}
disabled_colors={disabled}, {mantle}, {disabled}, {disabled}, {disabled}, {disabled}, {disabled}, {disabled}, {disabled}, {mantle}, {mantle}, {mantle}, {surface}, {disabled}, {acc}, {acc}, {mantle}, {disabled}, {surface}, {disabled}, {acc}
inactive_colors={fg}, {bg}, {fg}, {fg}, {disabled}, {fg}, {fg}, {fg}, {fg}, {bg}, {bg}, {mantle}, {surface}, {fg}, {acc}, {acc}, {mantle}, {fg}, {surface}, {fg}, {acc}
"""
