"""String templates rendered from a palette JSON object."""

from __future__ import annotations

from .colors import contrast_on, darken, hash_hex, palette_mode, rgb_css, strip_hash
from . import paths

POINTER_SIZE = 24
POINTER_THEME_DARK = "Bibata-Modern-Ice"
POINTER_THEME_LIGHT = "Bibata-Modern-Classic"


def pointer_theme(*, light: bool) -> str:
    """White Ice on dark palettes, black Classic on light — contrast, not match."""
    return POINTER_THEME_LIGHT if light else POINTER_THEME_DARK


def _h(palette: dict, key: str) -> str:
    return strip_hash(palette[key])


def hypr_theme_lua(palette: dict) -> str:
    def rgb(key: str) -> str:
        return rgb_css(palette[key])

    blue = _h(palette, "accentBlue")
    return f'''-- Generated by yahr-theme; do not edit.
return {{
    accent_rose     = "{rgb("accentRose")}",
    accent_coral    = "{rgb("accentCoral")}",
    accent_pink     = "{rgb("accentPink")}",
    accent_purple   = "{rgb("accentPurple")}",
    accent_red      = "{rgb("accentRed")}",
    accent_maroon   = "{rgb("accentMaroon")}",
    accent_orange   = "{rgb("accentOrange")}",
    accent_yellow   = "{rgb("accentYellow")}",
    accent_green    = "{rgb("accentGreen")}",
    accent_teal     = "{rgb("accentTeal")}",
    accent_cyan     = "{rgb("accentCyan")}",
    accent_sapphire = "{rgb("accentSapphire")}",
    accent_blue     = "{rgb("accentBlue")}",
    accent_lavender = "{rgb("accentLavender")}",

    fg_primary   = "{rgb("fgPrimary")}",
    fg_secondary = "{rgb("fgSecondary")}",
    fg_tertiary  = "{rgb("fgTertiary")}",

    border_2 = "{rgb("border2")}",
    border_1 = "{rgb("border1")}",
    border_0 = "{rgb("border0")}",

    surface_2 = "{rgb("surface2")}",
    surface_1 = "{rgb("surface1")}",
    surface_0 = "{rgb("surface0")}",

    bg_base   = "{rgb("bgBase")}",
    bg_mantle = "{rgb("bgMantle")}",
    bg_crust  = "{rgb("bgCrust")}",

    glass_accent = "rgba({blue}59)",
}}
'''


def ghostty_theme(palette: dict) -> str:
    fg = palette["fgPrimary"]
    bg = palette["bgBase"]
    acc = palette["accentBlue"]
    crust = palette["bgCrust"]
    red = palette["accentRed"]
    green = palette["accentGreen"]
    yellow = palette["accentYellow"]
    purple = palette["accentPurple"]
    cyan = palette["accentCyan"]
    surface1 = palette["surface1"]
    return f'''# Generated by yahr-theme — {palette["name"]}
palette = 0={crust}
palette = 1={red}
palette = 2={green}
palette = 3={yellow}
palette = 4={acc}
palette = 5={purple}
palette = 6={cyan}
palette = 7={fg}
palette = 8={surface1}
palette = 9={red}
palette = 10={green}
palette = 11={yellow}
palette = 12={acc}
palette = 13={purple}
palette = 14={cyan}
palette = 15={fg}
background = {bg}
foreground = {fg}
cursor-color = {fg}
cursor-text = {bg}
selection-background = {acc}
selection-foreground = {bg}
'''


def ghostty_config_base() -> str:
    return """# Ghostty — created by yahr-theme.
# Palette is written into the yahr-theme block below; keep the rest of
# this file for your own font / keybind / window settings.
font-family = Maple Mono NF
font-size = 13
window-padding-x = 8
window-padding-y = 8
window-decoration = false
confirm-close-surface = false
"""


def ghostty_config_block(*, light: bool, background_opacity: float = 1.0) -> str:
    theme = "light" if light else "dark"
    # Hyprland owns app-window transparency. Ghostty's GL buffer stays
    # opaque so compositor opacity is not applied twice.
    _ = background_opacity
    return f"""theme = yahr
window-theme = {theme}
background-opacity = 1.00
"""


def starship_toml(palette: dict) -> str:
    name = palette.get("name") or "Yahr"
    bg = palette["bgBase"]
    fg = palette["fgPrimary"]
    green = palette["accentGreen"]
    blue = palette["accentBlue"]
    red = palette["accentRed"]
    if palette_mode(palette) == "light":
        chip = hash_hex(darken(strip_hash(bg), 0.14))
    else:
        chip = palette["surface0"]
    on_os = contrast_on(green, dark=bg, light=fg)
    on_alert = contrast_on(red, dark=bg, light=fg)
    return f'''# Generated by yahr-theme — {name}

palette = "yahr"

format = """[󰣇 ](bg:base fg:os)[](fg:base bg:chip)$time[](fg:chip bg:base)$directory$git_branch$git_status$git_metrics$cmd_duration[](fg:base bg:os)$character"""

[palettes.yahr]
text = "{fg}"
base = "{bg}"
chip = "{chip}"
os = "{green}"
accent = "{blue}"
alert = "{red}"
on_os = "{on_os}"
on_alert = "{on_alert}"

[directory]
format = "[  $path ]($style)"
style = "fg:os bg:base"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[ $symbol$branch(:$remote_branch) ]($style)"
symbol = " "
style = "fg:os bg:base"

[git_status]
format = "[$all_status]($style)"
style = "fg:os bg:base"

[git_metrics]
format = "([+$added]($added_style)[-$deleted]($deleted_style))"
added_style = "fg:os bg:base"
deleted_style = "fg:alert bg:base"
disabled = false

[cmd_duration]
format = "[ 󱎫 $duration ]($style)"
style = "fg:accent bg:base"
min_time = 2000

[character]
# Closing  draws the pointed tip out of the status chip; without it the
# last powerline segment ends in a flat rectangle before the cursor.
success_symbol = "[ ➜](bold on_os bg:os)[](fg:os) "
error_symbol = "[ ✗](bold on_alert bg:alert)[](fg:alert) "

[time]
disabled = false
time_format = "%R"
style = "bg:chip"
format = "[ 󱑍 $time ](bg:chip fg:accent)"
'''


def _alpha_hex(opacity: float) -> str:
    n = int(round(max(0.0, min(1.0, opacity)) * 255))
    return f"{n:02x}"


def mako_style(palette: dict, settings: dict | None = None) -> dict:
    """Font + Hyprland window-border chrome for mako."""
    settings = settings or {}
    general = settings.get("general") or {}
    hypr = settings.get("hypr") or {}
    opacity = 1.0
    if hypr.get("borderTransparent", True):
        transparency = int(hypr.get("borderTransparency") or 65)
        opacity = max(0.0, min(1.0, (100 - transparency) / 100.0))
    # Mako is a solid stroke. Match Hyprland's overall border opacity rather
    # than the 35% accent stop used by Qt widget frames in gradient mode.
    alpha = _alpha_hex(opacity)
    acc = strip_hash(palette["accentBlue"])
    green = strip_hash(palette["accentGreen"])
    red = strip_hash(palette["accentRed"])
    return {
        "font": str(general.get("uiFont") or "Inter"),
        "border_size": 0 if hypr.get("showBorder", True) is False else int(hypr.get("borderSize") or 3),
        "border_radius": int(hypr.get("rounding") or 12),
        "border_color": f"#{acc}{alpha}",
        "low_border": f"#{green}{alpha}",
        "critical_border": f"#{red}{alpha}",
        "progress": f"over #{acc}{alpha}",
    }


def mako_config(palette: dict, *, font: str = "Inter", border_size: int = 3,
                border_radius: int = 12, border_color: str | None = None,
                low_border: str | None = None, critical_border: str | None = None,
                progress: str | None = None) -> str:
    bg = strip_hash(palette["bgBase"])
    fg = palette["fgPrimary"]
    acc = strip_hash(palette["accentBlue"])
    green = strip_hash(palette["accentGreen"])
    red = strip_hash(palette["accentRed"])
    border_color = border_color or f"#{acc}59"
    low_border = low_border or f"#{green}59"
    critical_border = critical_border or f"#{red}99"
    progress = progress or f"over #{acc}59"
    return f'''# Generated by yahr-theme — {palette["name"]}
font={font} 13
markup=1
max-visible=5
sort=-time
layer=overlay
anchor=top-right
margin=8
padding=14
border-size={border_size}
border-radius={border_radius}
background-color=#{bg}E8
text-color={fg}
border-color={border_color}
progress-color={progress}

default-timeout=10000
width=400
height=150
max-icon-size=48
group-by=app-name

[urgency=low]
border-color={low_border}
default-timeout=5000

[urgency=normal]
border-color={border_color}
default-timeout=10000

[urgency=critical]
border-color={critical_border}
default-timeout=0

icons=1
icon-path=/usr/share/icons/{'Papirus' if palette_mode(palette) == 'light' else 'Papirus-Dark'}
format=<b>%s</b>\\n%b
'''


def gtk_css(palette: dict) -> str:
    """GTK3/GTK4 overlay.

    Packaged themes (Materia forks in ~/.themes) and Adwaita key off
    theme_base_color for lists/icon views. libadwaita uses view_bg_color.
    Thunar's file grid is a GtkIconView, so both plus explicit iconview
    rules are required or the pane stays Adwaita's light grey.
    """
    bg = palette["bgBase"]
    mantle = palette["bgMantle"]
    crust = palette["bgCrust"]
    fg = palette["fgPrimary"]
    accent = palette["accentBlue"]
    accent_fg = contrast_on(accent, dark=bg, light="#ffffff")
    surface = palette["surface0"]
    surface1 = palette["surface1"]
    surface2 = palette["surface2"]
    border = palette["border0"]
    red = palette["accentRed"]
    green = palette["accentGreen"]
    yellow = palette["accentYellow"]
    return f'''/* Generated by yahr-theme — {palette["name"]} */

/* libadwaita / adw-gtk3 */
@define-color accent_color {accent};
@define-color accent_bg_color {accent};
@define-color accent_fg_color {accent_fg};
@define-color window_bg_color {bg};
@define-color window_fg_color {fg};
@define-color view_bg_color {mantle};
@define-color view_fg_color {fg};
@define-color headerbar_bg_color {mantle};
@define-color headerbar_fg_color {fg};
@define-color headerbar_backdrop_color {crust};
@define-color headerbar_border_color {border};
@define-color card_bg_color {surface};
@define-color card_fg_color {fg};
@define-color popover_bg_color {surface};
@define-color popover_fg_color {fg};
@define-color sidebar_bg_color {mantle};
@define-color sidebar_fg_color {fg};
@define-color sidebar_backdrop_color {crust};
@define-color destructive_bg_color {red};
@define-color destructive_fg_color {accent_fg};
@define-color success_bg_color {green};
@define-color warning_bg_color {yellow};
@define-color error_bg_color {red};
@define-color borders {border};

/* GTK3 / Materia (Catppuccin-Dark, Dracula, …) — Thunar icon view uses these */
@define-color theme_bg_color {bg};
@define-color theme_fg_color {fg};
@define-color theme_base_color {mantle};
@define-color theme_text_color {fg};
@define-color theme_selected_bg_color {accent};
@define-color theme_selected_fg_color {accent_fg};
@define-color insensitive_bg_color {surface};
@define-color insensitive_fg_color {palette["fgTertiary"]};
@define-color insensitive_base_color {surface};

window, .background, .csd {{
  background-color: {bg};
  color: {fg};
}}

headerbar, .titlebar {{
  background-color: {mantle};
  color: {fg};
}}

.sidebar, placessidebar {{
  background-color: {mantle};
  color: {fg};
}}

/* Thunar file grid / details / compact views */
.thunar .standard-view,
.thunar .view,
.thunar iconview,
.thunar treeview,
iconview,
.view,
treeview {{
  background-color: {mantle};
  color: {fg};
}}

.thunar .standard-view:selected,
.thunar iconview:selected,
.thunar treeview:selected,
iconview:selected,
.view:selected,
treeview:selected {{
  background-color: {accent};
  color: {accent_fg};
}}

entry, .entry {{
  background-color: {surface};
  color: {fg};
  border-color: {border};
}}

button {{
  background-image: none;
  background-color: {surface1};
  color: {fg};
}}

button:hover {{
  background-color: {surface2};
}}

button.suggested-action, button.default {{
  background-color: {accent};
  color: {accent_fg};
}}

selection, *:selected {{
  background-color: {accent};
  color: {accent_fg};
}}
'''


def gtk_settings_ini(gtk_theme: str, icon_theme: str, *, light: bool) -> str:
    prefer_dark = "0" if light else "1"
    pointer = pointer_theme(light=light)
    return f"""[Settings]
gtk-theme-name={gtk_theme}
gtk-icon-theme-name={icon_theme}
gtk-font-name=Inter 11
gtk-cursor-theme-name={pointer}
gtk-cursor-theme-size={POINTER_SIZE}
gtk-application-prefer-dark-theme={prefer_dark}
"""


def gtkrc2(gtk_theme: str, icon_theme: str, *, light: bool = False) -> str:
    pointer = pointer_theme(light=light)
    return f'''gtk-theme-name="{gtk_theme}"
gtk-icon-theme-name="{icon_theme}"
gtk-font-name="Inter 11"
gtk-cursor-theme-name="{pointer}"
gtk-cursor-theme-size={POINTER_SIZE}
gtk-application-prefer-dark-theme=1
'''


def gtk_theme_env(gtk_theme: str, icon_theme: str, *, light: bool = False) -> str:
    pointer = pointer_theme(light=light)
    return f'''# Generated by yahr-theme — sourced by launch-thunar.sh
export GTK_THEME="{gtk_theme}"
export GTK_ICON_THEME="{icon_theme}"
export XCURSOR_THEME="{pointer}"
export XCURSOR_SIZE="{POINTER_SIZE}"
export HYPRCURSOR_THEME="{pointer}"
export HYPRCURSOR_SIZE="{POINTER_SIZE}"
'''


def firefox_user_chrome(palette: dict) -> str:
    name = palette.get("name") or "Yahr"
    return """/* Generated by yahr-theme — {name}. Do not edit. */

:root {{
    --bg-base: {bg} !important;
    --surface0: {surface0} !important;
    --surface1: {surface1} !important;
    --fg-primary: {fg} !important;
    --fg-secondary: {fg2} !important;
    --accent-blue: {accent} !important;
    --accent-green: {green} !important;
    --accent-red: {red} !important;
    --accent-yellow: {yellow} !important;
}}

* {{
    letter-spacing: normal !important;
    word-spacing: normal !important;
}}

#navigator-toolbox,
#TabsToolbar,
#nav-bar,
#PersonalToolbar,
toolbar {{
    background-color: var(--bg-base) !important;
    background-image: none !important;
    border: none !important;
    box-shadow: none !important;
}}

#tabbrowser-tabs,
.tabbrowser-arrowscrollbox,
#TabsToolbar-customization-target {{
    border: none !important;
}}

.tabbrowser-tab,
.tabbrowser-tab > .tab-stack > .tab-background {{
    background-color: var(--surface0) !important;
    color: var(--fg-secondary) !important;
    border: none !important;
    border-radius: 0 !important;
    margin: 0 !important;
    padding: 0 !important;
    outline: none !important;
    box-shadow: none !important;
}}

.tabbrowser-tab[selected="true"],
.tabbrowser-tab[selected="true"] > .tab-stack > .tab-background {{
    background-color: var(--surface1) !important;
    border: none !important;
    box-shadow: none !important;
    outline: none !important;
}}

.tabbrowser-tab[selected="true"] .tab-label,
.tabbrowser-tab[selected="true"] .tab-text {{
    color: var(--fg-primary) !important;
}}

.tabbrowser-tab:hover:not([selected="true"]) > .tab-stack > .tab-background {{
    background-color: var(--surface1) !important;
}}

.tab-label,
.tab-text {{
    color: var(--fg-secondary) !important;
}}

.tabbrowser-tab::after,
.tabbrowser-tab::before,
.titlebar-spacer[type="pre-tabs"],
.titlebar-spacer[type="post-tabs"] {{
    display: none !important;
    border: none !important;
}}

.tab-content {{
    border: none !important;
    outline: none !important;
}}

#urlbar,
#urlbar-background,
#urlbar-input-container,
#searchbar,
.searchbar-textbox {{
    background-color: var(--surface1) !important;
    color: var(--fg-primary) !important;
    border: none !important;
    box-shadow: none !important;
    outline: none !important;
    -moz-appearance: none !important;
}}

#urlbar-input,
#urlbar input {{
    color: var(--fg-primary) !important;
    background-color: transparent !important;
}}

#urlbar[breakout][breakout-extend],
#urlbar[breakout][breakout-extend] > #urlbar-background,
#urlbar[focused="true"],
#urlbar[focused="true"] #urlbar-background,
#urlbar[open],
#urlbar[open] #urlbar-background,
#searchbar:focus-within,
#urlbar-container,
#search-container {{
    border: none !important;
    box-shadow: none !important;
    outline: none !important;
}}

#urlbar-input,
.searchbar-textbox {{
    color: var(--fg-primary) !important;
}}

#urlbar toolbarbutton,
#page-action-buttons > toolbarbutton,
#urlbar-zoom-button {{
    fill: var(--fg-primary) !important;
    color: var(--fg-primary) !important;
}}

#urlbar-results,
.urlbarView,
.search-panel-one-offs {{
    background-color: var(--surface0) !important;
    color: var(--fg-primary) !important;
    border-color: var(--surface1) !important;
}}

.urlbarView-row {{
    background-color: var(--surface0) !important;
    color: var(--fg-primary) !important;
}}

.urlbarView-row[selected] {{
    background-color: var(--accent-blue) !important;
    color: var(--bg-base) !important;
}}

toolbarbutton,
.toolbarbutton-1 {{
    fill: var(--fg-primary) !important;
    color: var(--fg-primary) !important;
}}

toolbarbutton:hover,
.toolbarbutton-1:hover {{
    background-color: var(--surface1) !important;
}}

#sidebar-box,
#sidebar-header {{
    background-color: var(--bg-base) !important;
    color: var(--fg-primary) !important;
    border-color: var(--surface1) !important;
}}

menupopup,
menu,
menuitem,
.panel-arrowcontent {{
    background-color: var(--surface0) !important;
    color: var(--fg-primary) !important;
    -moz-appearance: none !important;
}}

menupopup menu,
menupopup menuitem {{
    background-color: var(--surface0) !important;
    color: var(--fg-primary) !important;
}}

menupopup menu[_moz-menuactive="true"],
menupopup menuitem[_moz-menuactive="true"],
menuitem:hover {{
    background-color: var(--accent-blue) !important;
    color: var(--bg-base) !important;
}}

#PlacesToolbarItems > .bookmark-item {{
    color: var(--fg-primary) !important;
}}

#PlacesToolbarItems > .bookmark-item:hover {{
    background-color: var(--surface1) !important;
}}

findbar {{
    background-color: var(--surface0) !important;
    border-color: var(--surface1) !important;
}}

.findbar-textbox {{
    background-color: var(--surface1) !important;
    color: var(--fg-primary) !important;
}}

.tab-line {{
    background-color: var(--accent-blue) !important;
}}

notification,
.notificationbox-stack {{
    background-color: var(--surface1) !important;
    color: var(--fg-primary) !important;
}}
""".format(
        name=name,
        bg=palette["bgBase"],
        surface0=palette["surface0"],
        surface1=palette["surface1"],
        fg=palette["fgPrimary"],
        fg2=palette["fgSecondary"],
        accent=palette.get("accentOrange") or palette["accentBlue"],
        green=palette["accentGreen"],
        red=palette["accentRed"],
        yellow=palette["accentYellow"],
    )


def firefox_user_js(*, light: bool) -> str:
    toolbar = 1 if light else 0
    dark = 0 if light else 1
    return f'''// >>> yahr-theme
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("browser.theme.toolbar-theme", {toolbar});
user_pref("ui.systemUsesDarkTheme", {dark});
// <<< yahr-theme
'''


def cursor_color_customizations(palette: dict) -> dict:
    """Workbench tokens Cursor/VS Code consume as --vscode-* CSS variables."""
    bg = palette["bgBase"]
    mantle = palette["bgMantle"]
    crust = palette["bgCrust"]
    fg = palette["fgPrimary"]
    fg2 = palette["fgSecondary"]
    fg3 = palette["fgTertiary"]
    s0 = palette["surface0"]
    s1 = palette["surface1"]
    s2 = palette["surface2"]
    b0 = palette["border0"]
    acc = palette["accentBlue"]
    acc_fg = contrast_on(acc, dark=crust, light=fg)
    red = palette["accentRed"]
    green = palette["accentGreen"]
    yellow = palette["accentYellow"]
    cyan = palette["accentCyan"]
    orange = palette["accentOrange"]
    purple = palette["accentPurple"]
    pink = palette["accentPink"]
    sel = palette.get("glassAccent") or (acc + "59")
    if not str(sel).startswith("#"):
        sel = "#" + str(sel)
    return {
        "foreground": fg,
        "focusBorder": acc,
        "selection.background": sel,
        "widget.shadow": crust,
        "descriptionForeground": fg3,
        "errorForeground": red,
        "icon.foreground": fg2,
        "sash.hoverBorder": acc,
        "titleBar.activeBackground": mantle,
        "titleBar.activeForeground": fg,
        "titleBar.inactiveBackground": crust,
        "titleBar.inactiveForeground": fg3,
        "titleBar.border": crust,
        "activityBar.background": crust,
        "activityBar.foreground": fg,
        "activityBar.inactiveForeground": fg3,
        "activityBar.border": crust,
        "activityBar.activeBorder": acc,
        "activityBarBadge.background": acc,
        "activityBarBadge.foreground": acc_fg,
        "sideBar.background": mantle,
        "sideBar.foreground": fg,
        "sideBar.border": crust,
        "sideBarTitle.foreground": fg2,
        "sideBarSectionHeader.background": mantle,
        "sideBarSectionHeader.foreground": fg2,
        "statusBar.background": crust,
        "statusBar.foreground": fg,
        "statusBar.border": crust,
        "statusBar.noFolderBackground": crust,
        "statusBar.debuggingBackground": orange,
        "statusBar.debuggingForeground": crust,
        "statusBarItem.hoverBackground": s0,
        "statusBarItem.remoteBackground": acc,
        "statusBarItem.remoteForeground": acc_fg,
        "editorGroupHeader.tabsBackground": mantle,
        "editorGroupHeader.noTabsBackground": mantle,
        "editorGroup.border": crust,
        "tab.activeBackground": bg,
        "tab.inactiveBackground": mantle,
        "tab.activeForeground": fg,
        "tab.inactiveForeground": fg3,
        "tab.border": crust,
        "tab.activeBorderTop": acc,
        "tab.hoverBackground": s0,
        "editor.background": bg,
        "editor.foreground": fg,
        "editor.lineHighlightBackground": s0,
        "editor.selectionBackground": sel,
        "editor.inactiveSelectionBackground": s0,
        "editor.wordHighlightBackground": s1,
        "editorCursor.foreground": acc,
        "editorLineNumber.foreground": fg3,
        "editorLineNumber.activeForeground": fg2,
        "editorWhitespace.foreground": b0,
        "editorIndentGuide.background": s0,
        "editorIndentGuide.activeBackground": s2,
        "editorRuler.foreground": s0,
        "editorGutter.background": bg,
        "editorWidget.background": s0,
        "editorWidget.foreground": fg,
        "editorWidget.border": b0,
        "editorSuggestWidget.background": s0,
        "editorSuggestWidget.foreground": fg,
        "editorSuggestWidget.selectedBackground": s1,
        "editorSuggestWidget.border": b0,
        "editorHoverWidget.background": s0,
        "editorHoverWidget.foreground": fg,
        "editorHoverWidget.border": b0,
        "peekView.border": acc,
        "peekViewEditor.background": mantle,
        "peekViewResult.background": s0,
        "peekViewTitle.background": crust,
        "panel.background": mantle,
        "panel.border": crust,
        "panelTitle.activeForeground": fg,
        "panelTitle.inactiveForeground": fg3,
        "panelTitle.activeBorder": acc,
        "terminal.background": bg,
        "terminal.foreground": fg,
        "terminal.ansiBlack": crust,
        "terminal.ansiRed": red,
        "terminal.ansiGreen": green,
        "terminal.ansiYellow": yellow,
        "terminal.ansiBlue": acc,
        "terminal.ansiMagenta": purple,
        "terminal.ansiCyan": cyan,
        "terminal.ansiWhite": fg,
        "terminal.ansiBrightBlack": fg3,
        "terminal.ansiBrightRed": red,
        "terminal.ansiBrightGreen": green,
        "terminal.ansiBrightYellow": yellow,
        "terminal.ansiBrightBlue": acc,
        "terminal.ansiBrightMagenta": pink,
        "terminal.ansiBrightCyan": cyan,
        "terminal.ansiBrightWhite": fg,
        "input.background": s0,
        "input.foreground": fg,
        "input.border": b0,
        "input.placeholderForeground": fg3,
        "inputOption.activeBorder": acc,
        "dropdown.background": s0,
        "dropdown.foreground": fg,
        "dropdown.border": b0,
        "button.background": acc,
        "button.foreground": acc_fg,
        "button.hoverBackground": s2,
        "button.secondaryBackground": s1,
        "button.secondaryForeground": fg,
        "checkbox.background": s0,
        "checkbox.foreground": fg,
        "checkbox.border": b0,
        "badge.background": acc,
        "badge.foreground": acc_fg,
        "progressBar.background": acc,
        "list.activeSelectionBackground": s1,
        "list.activeSelectionForeground": fg,
        "list.inactiveSelectionBackground": s0,
        "list.hoverBackground": s0,
        "list.focusBackground": s1,
        "list.highlightForeground": acc,
        "list.errorForeground": red,
        "list.warningForeground": yellow,
        "tree.indentGuidesStroke": s1,
        "commandCenter.background": mantle,
        "commandCenter.foreground": fg,
        "commandCenter.border": crust,
        "commandCenter.activeBackground": s0,
        "notifications.background": s0,
        "notifications.foreground": fg,
        "notifications.border": b0,
        "notificationCenterHeader.background": mantle,
        "notificationCenterHeader.foreground": fg,
        "menu.background": s0,
        "menu.foreground": fg,
        "menu.selectionBackground": s1,
        "menu.selectionForeground": fg,
        "menu.separatorBackground": s1,
        "menubar.selectionBackground": s0,
        "quickInput.background": s0,
        "quickInput.foreground": fg,
        "pickerGroup.foreground": acc,
        "scrollbarSlider.background": s1 + "99",
        "scrollbarSlider.hoverBackground": s2 + "bb",
        "scrollbarSlider.activeBackground": acc + "99",
        "minimap.background": bg,
        "gitDecoration.modifiedResourceForeground": yellow,
        "gitDecoration.addedResourceForeground": green,
        "gitDecoration.deletedResourceForeground": red,
        "gitDecoration.untrackedResourceForeground": cyan,
        "gitDecoration.ignoredResourceForeground": fg3,
        "diffEditor.insertedTextBackground": green + "33",
        "diffEditor.removedTextBackground": red + "33",
        "textLink.foreground": acc,
        "textLink.activeForeground": cyan,
        "textCodeBlock.background": s0,
        "textBlockQuote.background": s0,
        "textSeparator.foreground": s1,
        "breadcrumb.foreground": fg3,
        "breadcrumb.focusForeground": fg,
        "breadcrumb.activeSelectionForeground": acc,
        "editorOverviewRuler.border": crust,
        "editorBracketMatch.background": sel,
        "editorBracketMatch.border": acc,
    }


def cursor_token_customizations(palette: dict) -> dict:
    return {
        "comments": palette["fgTertiary"],
        "strings": palette["accentGreen"],
        "keywords": palette["accentRed"],
        "functions": palette["accentBlue"],
        "numbers": palette["accentPurple"],
        "types": palette["accentYellow"],
        "variables": palette["fgPrimary"],
        "textMateRules": [
            {"scope": "comment", "settings": {"foreground": palette["fgTertiary"], "fontStyle": "italic"}},
            {"scope": "string", "settings": {"foreground": palette["accentGreen"]}},
            {"scope": "keyword", "settings": {"foreground": palette["accentRed"]}},
            {"scope": "storage.type", "settings": {"foreground": palette["accentRed"]}},
            {"scope": "entity.name.function", "settings": {"foreground": palette["accentBlue"]}},
            {"scope": "variable", "settings": {"foreground": palette["fgPrimary"]}},
            {"scope": "constant.numeric", "settings": {"foreground": palette["accentPurple"]}},
            {"scope": "entity.name.type", "settings": {"foreground": palette["accentYellow"]}},
            {"scope": "support.type", "settings": {"foreground": palette["accentYellow"]}},
            {"scope": "punctuation.definition.tag", "settings": {"foreground": palette["accentRed"]}},
            {"scope": "entity.other.attribute-name", "settings": {"foreground": palette["accentYellow"]}},
        ],
    }


def hyprlock_conf(palette: dict) -> str:
    bg = strip_hash(palette["bgBase"])
    surface = strip_hash(palette["surface0"])
    acc = strip_hash(palette["accentBlue"])
    green = strip_hash(palette["accentGreen"])
    red = strip_hash(palette["accentRed"])
    yellow = strip_hash(palette["accentYellow"])
    cyan = strip_hash(palette["accentCyan"])
    fg = strip_hash(palette["fgPrimary"])
    fg2 = strip_hash(palette["fgSecondary"])
    fg3 = strip_hash(palette["fgTertiary"])
    lock_py = str(paths.yahr_config() / "lock-info.py")
    lock_str = str(paths.home() / ".cache/yahr/lock-strings")
    return f'''# Generated by yahr-theme — {palette["name"]}
# 4-col grid: date 1x1 | time 1x3
#            system 1x1 | battery 1x1 | avatar 2x2
#            weather 1x2              | avatar 2x2
$font = Maple Mono NF
$ui = Inter
$icons = Symbols Nerd Font
$plate = rgba({bg}F2)
$card = rgba({surface}E6)
$muted = rgba({fg3}FF)

general {{
    hide_cursor = false
    ignore_empty_input = true
}}

animations {{
    enabled = true
    bezier = easeInOut, 0.42, 0, 0.58, 1
    animation = fadeIn, 1, 4, easeInOut
    animation = fadeOut, 1, 4, easeInOut
    animation = inputFieldDots, 1, 2, easeInOut
}}

background {{
    monitor =
    path = screenshot
    blur_passes = 4
    blur_size = 8
    brightness = 0.72
    contrast = 0.9
}}

# Bar-colored plate behind the whole dashboard (tiles + password bar).
shape {{
    monitor =
    size = 952, 788
    color = $plate
    rounding = 28
    position = 0, 0
    halign = center
    valign = center
    zindex = 0
}}

# Tiles sit on the plate with no drop shadows.
shape {{
    monitor =
    size = 220, 220
    color = $card
    rounding = 22
    position = -354, 272
    halign = center
    valign = center
    zindex = 1
}}

shape {{
    monitor =
    size = 692, 220
    color = $card
    rounding = 22
    position = 118, 272
    halign = center
    valign = center
    zindex = 1
}}

shape {{
    monitor =
    size = 220, 220
    color = $card
    rounding = 22
    position = -354, 36
    halign = center
    valign = center
    zindex = 1
}}

shape {{
    monitor =
    size = 220, 220
    color = $card
    rounding = 22
    position = -118, 36
    halign = center
    valign = center
    zindex = 1
}}

shape {{
    monitor =
    size = 456, 456
    color = $card
    rounding = 22
    position = 236, -82
    halign = center
    valign = center
    zindex = 1
}}

shape {{
    monitor =
    size = 456, 220
    color = $card
    rounding = 22
    position = -236, -200
    halign = center
    valign = center
    zindex = 1
}}

shape {{
    monitor =
    size = 928, 56
    color = $card
    rounding = 22
    position = 0, -354
    halign = center
    valign = center
    zindex = 1
}}

# --- time: group centered in the 1x3 tile ---
label {{
    monitor =
    text = cmd[update:1000] python3 {lock_py} time
    color = rgba({fg}FF)
    font_size = 74
    font_family = Inter ExtraBold
    position = 70, 272
    halign = center
    valign = center
    zindex = 2
}}

label {{
    monitor =
    text = cmd[update:1000] python3 {lock_py} ampm
    color = rgba({fg2}FF)
    font_size = 22
    font_family = $ui
    position = 268, 260
    halign = center
    valign = center
    zindex = 2
}}

# --- date 1x1 ---
label {{
    monitor =
    text = cmd[update:60000] python3 {lock_py} date-weekday
    color = rgba({fg2}FF)
    font_size = 16
    font_family = $ui
    position = -376, 320
    halign = center
    valign = center
    zindex = 2
}}

label {{
    monitor =
    text = cmd[update:60000] python3 {lock_py} date-month
    color = rgba({acc}FF)
    font_size = 16
    font_family = $ui
    position = -332, 320
    halign = center
    valign = center
    zindex = 2
}}

label {{
    monitor =
    text = cmd[update:60000] python3 {lock_py} date-day
    color = rgba({fg}FF)
    font_size = 64
    font_family = Inter ExtraBold
    position = -354, 272
    halign = center
    valign = center
    zindex = 2
}}

label {{
    monitor =
    text = cmd[update:60000] python3 {lock_py} date-year
    color = rgba({acc}FF)
    font_size = 18
    font_family = $ui
    position = -354, 222
    halign = center
    valign = center
    zindex = 2
}}

# --- avatar 2x2 ---
image {{
    monitor =
    path = ~/.face.icon
    size = 456
    rounding = 22
    border_size = 0
    position = 236, -82
    halign = center
    valign = center
    zindex = 2
}}

# --- weather 1x2 (current + 3-day) ---
label {{
    monitor =
    text = cmd[update:60000] cat {lock_str}/weather-icon
    color = rgba({cyan}FF)
    font_size = 36
    font_family = $icons
    position = -400, -168
    halign = center
    valign = center
    zindex = 2
}}

label {{
    monitor =
    text = cmd[update:60000] cat {lock_str}/weather-temp
    color = rgba({fg}FF)
    font_size = 26
    font_family = Inter ExtraBold
    position = -400, -208
    halign = center
    valign = center
    zindex = 2
}}

label {{
    monitor =
    text = cmd[update:60000] cat {lock_str}/weather-cond
    color = rgba({fg2}FF)
    font_size = 11
    font_family = $ui
    text_align = center
    position = -400, -242
    halign = center
    valign = center
    zindex = 2
}}

label {{
    monitor =
    text = cmd[update:60000] cat {lock_str}/forecast-0-day
    color = $muted
    font_size = 12
    font_family = $ui
    position = -268, -148
    halign = center
    valign = center
    zindex = 2
}}
label {{
    monitor =
    text = cmd[update:60000] cat {lock_str}/forecast-0-temps
    color = rgba({fg}FF)
    font_size = 13
    font_family = $ui
    position = -268, -174
    halign = center
    valign = center
    zindex = 2
}}
label {{
    monitor =
    text = cmd[update:60000] cat {lock_str}/forecast-0-icon
    color = rgba({cyan}FF)
    font_size = 20
    font_family = $icons
    position = -268, -204
    halign = center
    valign = center
    zindex = 2
}}
label {{
    monitor =
    text = cmd[update:60000] cat {lock_str}/forecast-0-cond
    color = rgba({fg2}FF)
    font_size = 10
    font_family = $ui
    text_align = center
    position = -268, -236
    halign = center
    valign = center
    zindex = 2
}}

label {{
    monitor =
    text = cmd[update:60000] cat {lock_str}/forecast-1-day
    color = $muted
    font_size = 12
    font_family = $ui
    position = -172, -148
    halign = center
    valign = center
    zindex = 2
}}
label {{
    monitor =
    text = cmd[update:60000] cat {lock_str}/forecast-1-temps
    color = rgba({fg}FF)
    font_size = 13
    font_family = $ui
    position = -172, -174
    halign = center
    valign = center
    zindex = 2
}}
label {{
    monitor =
    text = cmd[update:60000] cat {lock_str}/forecast-1-icon
    color = rgba({cyan}FF)
    font_size = 20
    font_family = $icons
    position = -172, -204
    halign = center
    valign = center
    zindex = 2
}}
label {{
    monitor =
    text = cmd[update:60000] cat {lock_str}/forecast-1-cond
    color = rgba({fg2}FF)
    font_size = 10
    font_family = $ui
    text_align = center
    position = -172, -236
    halign = center
    valign = center
    zindex = 2
}}

label {{
    monitor =
    text = cmd[update:60000] cat {lock_str}/forecast-2-day
    color = $muted
    font_size = 12
    font_family = $ui
    position = -82, -148
    halign = center
    valign = center
    zindex = 2
}}
label {{
    monitor =
    text = cmd[update:60000] cat {lock_str}/forecast-2-temps
    color = rgba({fg}FF)
    font_size = 13
    font_family = $ui
    position = -82, -174
    halign = center
    valign = center
    zindex = 2
}}
label {{
    monitor =
    text = cmd[update:60000] cat {lock_str}/forecast-2-icon
    color = rgba({cyan}FF)
    font_size = 20
    font_family = $icons
    position = -82, -204
    halign = center
    valign = center
    zindex = 2
}}
label {{
    monitor =
    text = cmd[update:60000] cat {lock_str}/forecast-2-cond
    color = rgba({fg2}FF)
    font_size = 10
    font_family = $ui
    text_align = center
    position = -82, -236
    halign = center
    valign = center
    zindex = 2
}}

# --- battery 1x1 ---
label {{
    monitor =
    text = cmd[update:20000] python3 {lock_py} battery-icon
    color = rgba({green}FF)
    font_size = 36
    font_family = $icons
    position = -118, 72
    halign = center
    valign = center
    zindex = 2
}}

label {{
    monitor =
    text = cmd[update:20000] python3 {lock_py} battery-pct
    color = rgba({green}FF)
    font_size = 28
    font_family = Inter ExtraBold
    position = -118, 24
    halign = center
    valign = center
    zindex = 2
}}

label {{
    monitor =
    text = cmd[update:20000] python3 {lock_py} battery-sub
    color = rgba({fg2}FF)
    font_size = 12
    font_family = $ui
    position = -118, -18
    halign = center
    valign = center
    zindex = 2
}}

# --- system 1x1: mark + host block ---
image {{
    monitor =
    path = /usr/share/pixmaps/archlinux-logo.png
    size = 56
    rounding = 0
    border_size = 0
    position = -354, 94
    halign = center
    valign = center
    zindex = 2
}}

label {{
    monitor =
    text = cmd[update:60000] cat {lock_str}/host-block
    color = rgba({fg}FF)
    font_size = 10
    font_family = $font
    position = -354, 10
    halign = center
    valign = center
    zindex = 2
}}

# --- password ---
input-field {{
    monitor =
    size = 888, 44
    outline_thickness = 0
    inner_color = rgba({bg}00)
    outer_color = rgba({bg}00)
    check_color = rgba({green}FF)
    fail_color = rgba({red}FF)
    font_color = rgba({fg}FF)
    fade_on_empty = false
    rounding = 16
    font_family = $ui
    placeholder_text = type password to unlock
    fail_text = $FAIL ($ATTEMPTS)
    dots_spacing = 0.35
    dots_center = true
    dots_size = 0.25
    position = 0, -354
    halign = center
    valign = center
    zindex = 3
}}
'''


def qt6ct_colors(palette: dict) -> str:
    def argb(key: str) -> str:
        return "#ff" + strip_hash(palette[key])

    fg = argb("fgPrimary")
    bg = argb("bgBase")
    acc = argb("accentBlue")
    surface = argb("surface0")
    mantle = argb("bgMantle")
    disabled = argb("fgTertiary")
    return f"""[ColorScheme]
active_colors={fg}, {bg}, {fg}, {fg}, {disabled}, {fg}, {fg}, {fg}, {fg}, {bg}, {bg}, {mantle}, {surface}, {fg}, {acc}, {acc}, {mantle}, {fg}, {surface}, {fg}, {acc}
disabled_colors={disabled}, {mantle}, {disabled}, {disabled}, {disabled}, {disabled}, {disabled}, {disabled}, {disabled}, {mantle}, {mantle}, {mantle}, {surface}, {disabled}, {acc}, {acc}, {mantle}, {disabled}, {surface}, {disabled}, {acc}
inactive_colors={fg}, {bg}, {fg}, {fg}, {disabled}, {fg}, {fg}, {fg}, {fg}, {bg}, {bg}, {mantle}, {surface}, {fg}, {acc}, {acc}, {mantle}, {fg}, {surface}, {fg}, {acc}
"""
